name: Daily Bible Verse Update

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:     # Manual trigger
  push:
    branches: [ main ]
    paths: [ 'src/**', '.github/workflows/**', 'Cargo.toml' ]

permissions:
  contents: write
  actions: read

env:
  CARGO_TERM_COLOR: always

jobs:
  update-daily-verse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Build terminal-bible CLI
      run: cargo build --release
      
    - name: Create data directory
      run: mkdir -p data/
      
    - name: Fetch daily Bible verse
      run: |
        echo "Fetching daily Bible verse..."
        ./target/release/terminal-bible > data/daily-verse-$(date +%Y-%m-%d).txt 2>&1
        
        echo "Captured verse:"
        cat data/daily-verse-$(date +%Y-%m-%d).txt
        
    - name: Update README with latest verse
      run: |
        # Clean the verse content for README
        cat data/daily-verse-$(date +%Y-%m-%d).txt | \
          sed 's/\x1b\[[0-9;]*m//g' | \
          sed 's/[╭╮╰╯─━❝✳]//g' | \
          sed 's/^[ ]*//g' | \
          grep -v "^TERMINAL BIBLE$" | \
          grep -v "^$" | \
          head -20 > verse_content.txt
        
        # Store today's date in a variable
        TODAY_DATE=$(date +%Y-%m-%d)
        
        # Generate daily verse section
        cat > new_daily_section.md << EOF
        <!-- DAILY_VERSE_START -->
        ## Today's Verse ($TODAY_DATE)
        EOF
        cat verse_content.txt >> new_daily_section.md
        cat >> new_daily_section.md << 'EOF'
        <!-- DAILY_VERSE_END -->
        EOF
        
        # Update README at the correct position
        awk '
        {
          print
        }
        /<!-- DAILY_VERSE_START -->/ {
          while (getline && !/<!-- DAILY_VERSE_END -->/) {}
          system("cat new_daily_section.md")
          next
        }' README.md > README.md.new
        
        # Replace old README with updated one
        mv README.md.new README.md
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        
        # Add the files
        git add data/
        git add README.md
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily Bible verse update - $(date +%Y-%m-%d)"
          
          # Push using the GitHub token
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          
          echo "Successfully pushed daily verse update!"
        fi

  test-terminal-bible-cli:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Build and test CLI
      run: |
        cargo build --release
        echo "Testing daily verse:"
        ./target/release/terminal-bible
        echo "Testing specific verse:"
        ./target/release/terminal-bible john3-16
